<?php


 function autoload_aefdbdded44c7c4ce86e33e56c69d662($class)
{
    $classes = array(
        'HotelService' => __DIR__ .'/HotelService.php',
        'HotelSearchRequest' => __DIR__ .'/HotelSearchRequest.php',
        'ArrayOfRoomGuest' => __DIR__ .'/ArrayOfRoomGuest.php',
        'RoomGuest' => __DIR__ .'/RoomGuest.php',
        'ArrayOfInt' => __DIR__ .'/ArrayOfInt.php',
        'Filters' => __DIR__ .'/Filters.php',
        'HotelRatingInput' => __DIR__ .'/HotelRatingInput.php',
        'OrderByFilter' => __DIR__ .'/OrderByFilter.php',
        'AuthenticationData' => __DIR__ .'/AuthenticationData.php',
        'HotelSearchResponse' => __DIR__ .'/HotelSearchResponse.php',
        'ResponseStatus' => __DIR__ .'/ResponseStatus.php',
        'ArrayOfHotel_Result' => __DIR__ .'/ArrayOfHotel_Result.php',
        'Hotel_Result' => __DIR__ .'/Hotel_Result.php',
        'HotelInfo' => __DIR__ .'/HotelInfo.php',
        'HotelInfoHotelRating' => __DIR__ .'/HotelInfoHotelRating.php',
        'MinHotelPrice' => __DIR__ .'/MinHotelPrice.php',
        'HotelRoomAvailabilityRequest' => __DIR__ .'/HotelRoomAvailabilityRequest.php',
        'HotelRoomAvailabilityResponse' => __DIR__ .'/HotelRoomAvailabilityResponse.php',
        'ArrayOfHotel_Room' => __DIR__ .'/ArrayOfHotel_Room.php',
        'Hotel_Room' => __DIR__ .'/Hotel_Room.php',
        'RoomRate' => __DIR__ .'/RoomRate.php',
        'ArrayOfDayRate' => __DIR__ .'/ArrayOfDayRate.php',
        'DayRate' => __DIR__ .'/DayRate.php',
        'ArrayOfSupplement' => __DIR__ .'/ArrayOfSupplement.php',
        'Supplement' => __DIR__ .'/Supplement.php',
        'SupplementType' => __DIR__ .'/SupplementType.php',
        'SupmtChargeType' => __DIR__ .'/SupmtChargeType.php',
        'RoomInformation' => __DIR__ .'/RoomInformation.php',
        'ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'ArrayOfString1' => __DIR__ .'/ArrayOfString1.php',
        'BookingOptions' => __DIR__ .'/BookingOptions.php',
        'RoomCombination' => __DIR__ .'/RoomCombination.php',
        'HotelCancellationPolicyRequest' => __DIR__ .'/HotelCancellationPolicyRequest.php',
        'HotelCancellationPolicyResponse' => __DIR__ .'/HotelCancellationPolicyResponse.php',
        'CancelPolicies' => __DIR__ .'/CancelPolicies.php',
        'CancelPolicy' => __DIR__ .'/CancelPolicy.php',
        'CancellationChargeTypeForHotel' => __DIR__ .'/CancellationChargeTypeForHotel.php',
        'PolicyFormat' => __DIR__ .'/PolicyFormat.php',
        'ArrayOfString2' => __DIR__ .'/ArrayOfString2.php',
        'HotelBookRequest' => __DIR__ .'/HotelBookRequest.php',
        'ArrayOfGuest' => __DIR__ .'/ArrayOfGuest.php',
        'Guest' => __DIR__ .'/Guest.php',
        'GuestType' => __DIR__ .'/GuestType.php',
        'AddressInfo' => __DIR__ .'/AddressInfo.php',
        'PaymentInfo' => __DIR__ .'/PaymentInfo.php',
        'PaymentModeType' => __DIR__ .'/PaymentModeType.php',
        'ArrayOfRequestedRooms' => __DIR__ .'/ArrayOfRequestedRooms.php',
        'RequestedRooms' => __DIR__ .'/RequestedRooms.php',
        'Rate' => __DIR__ .'/Rate.php',
        'ArrayOfSuppInfo' => __DIR__ .'/ArrayOfSuppInfo.php',
        'SuppInfo' => __DIR__ .'/SuppInfo.php',
        'SuppChargeType' => __DIR__ .'/SuppChargeType.php',
        'ArrayOfSpecialRequest' => __DIR__ .'/ArrayOfSpecialRequest.php',
        'SpecialRequest' => __DIR__ .'/SpecialRequest.php',
        'HotelBookResponse' => __DIR__ .'/HotelBookResponse.php',
        'APIHotelBookingStatus' => __DIR__ .'/APIHotelBookingStatus.php',
        'AvailabilityAndPricingRequest' => __DIR__ .'/AvailabilityAndPricingRequest.php',
        'AvailabilityAndPricingResponse' => __DIR__ .'/AvailabilityAndPricingResponse.php',
        'HotelCancellationPolicies' => __DIR__ .'/HotelCancellationPolicies.php',
        'PriceVerification' => __DIR__ .'/PriceVerification.php',
        'PriceVerificationStatus' => __DIR__ .'/PriceVerificationStatus.php',
        'AccountInfo' => __DIR__ .'/AccountInfo.php',
        'AccountBalance' => __DIR__ .'/AccountBalance.php',
        'HotelDetailsVerification' => __DIR__ .'/HotelDetailsVerification.php',
        'HotelDetailsVerificationStatus' => __DIR__ .'/HotelDetailsVerificationStatus.php',
        'HotelBookingDetailRequest' => __DIR__ .'/HotelBookingDetailRequest.php',
        'HotelBookingDetailResponse' => __DIR__ .'/HotelBookingDetailResponse.php',
        'APIBookingDetail' => __DIR__ .'/APIBookingDetail.php',
        'ArrayOfRoomDetails' => __DIR__ .'/ArrayOfRoomDetails.php',
        'RoomDetails' => __DIR__ .'/RoomDetails.php',
        'ArrayOfSupp_info' => __DIR__ .'/ArrayOfSupp_info.php',
        'Supp_info' => __DIR__ .'/Supp_info.php',
        'AmendmentDetails' => __DIR__ .'/AmendmentDetails.php',
        'AgencyDetails' => __DIR__ .'/AgencyDetails.php',
        'AOTNumbers' => __DIR__ .'/AOTNumbers.php',
        'GenerateInvoiceRequest' => __DIR__ .'/GenerateInvoiceRequest.php',
        'GenerateInvoiceResponse' => __DIR__ .'/GenerateInvoiceResponse.php',
        'AmendmentRequest' => __DIR__ .'/AmendmentRequest.php',
        'AmendmentRequestType' => __DIR__ .'/AmendmentRequestType.php',
        'AmendmentType' => __DIR__ .'/AmendmentType.php',
        'PriceChange' => __DIR__ .'/PriceChange.php',
        'AmendInformation' => __DIR__ .'/AmendInformation.php',
        'CheckInReq' => __DIR__ .'/CheckInReq.php',
        'CheckOutReq' => __DIR__ .'/CheckOutReq.php',
        'ArrayOfRoomReq' => __DIR__ .'/ArrayOfRoomReq.php',
        'RoomReq' => __DIR__ .'/RoomReq.php',
        'AmendGuestReq' => __DIR__ .'/AmendGuestReq.php',
        'AmendActionReq' => __DIR__ .'/AmendActionReq.php',
        'RoomRequested' => __DIR__ .'/RoomRequested.php',
        'AmendmentResponse' => __DIR__ .'/AmendmentResponse.php',
        'RequestStatus' => __DIR__ .'/RequestStatus.php',
        'ApprovalInformation' => __DIR__ .'/ApprovalInformation.php',
        'ArrayOfRoomPriceRes' => __DIR__ .'/ArrayOfRoomPriceRes.php',
        'RoomPriceRes' => __DIR__ .'/RoomPriceRes.php',
        'TotalPrice' => __DIR__ .'/TotalPrice.php',
        'AmendmentRequested' => __DIR__ .'/AmendmentRequested.php',
        'CheckInRes' => __DIR__ .'/CheckInRes.php',
        'DateActionRes' => __DIR__ .'/DateActionRes.php',
        'CheckOutRes' => __DIR__ .'/CheckOutRes.php',
        'ArrayOfRoomRes' => __DIR__ .'/ArrayOfRoomRes.php',
        'RoomRes' => __DIR__ .'/RoomRes.php',
        'AmendGuestRes' => __DIR__ .'/AmendGuestRes.php',
        'AmendActionRes' => __DIR__ .'/AmendActionRes.php',
        'HotelCancelRequest' => __DIR__ .'/HotelCancelRequest.php',
        'CancelRequestType' => __DIR__ .'/CancelRequestType.php',
        'HotelCancelResponse' => __DIR__ .'/HotelCancelResponse.php',
        'HotelCancelStatus' => __DIR__ .'/HotelCancelStatus.php',
        'CountryListRequest' => __DIR__ .'/CountryListRequest.php',
        'CountryListResponse' => __DIR__ .'/CountryListResponse.php',
        'ArrayOfCountryList' => __DIR__ .'/ArrayOfCountryList.php',
        'CountryList' => __DIR__ .'/CountryList.php',
        'DestinationCityListRequest' => __DIR__ .'/DestinationCityListRequest.php',
        'DestinationCityListResponse' => __DIR__ .'/DestinationCityListResponse.php',
        'ArrayOfCityList' => __DIR__ .'/ArrayOfCityList.php',
        'CityList' => __DIR__ .'/CityList.php',
        'TopDestinationsRequest' => __DIR__ .'/TopDestinationsRequest.php',
        'TopDestinationsResponse' => __DIR__ .'/TopDestinationsResponse.php',
        'HotelDetailsRequest' => __DIR__ .'/HotelDetailsRequest.php',
        'HotelDetailsResponse' => __DIR__ .'/HotelDetailsResponse.php',
        'APIHotelDetails' => __DIR__ .'/APIHotelDetails.php',
        'ArrayOfString3' => __DIR__ .'/ArrayOfString3.php',
        'ArrayOfString4' => __DIR__ .'/ArrayOfString4.php',
        'ArrayOfString5' => __DIR__ .'/ArrayOfString5.php',
        'ArrayOfRoomInfo' => __DIR__ .'/ArrayOfRoomInfo.php',
        'RoomInfo' => __DIR__ .'/RoomInfo.php',
        'ArrayOfString6' => __DIR__ .'/ArrayOfString6.php',
        'ArrayOfString7' => __DIR__ .'/ArrayOfString7.php',
        'HotelCodesRequest' => __DIR__ .'/HotelCodesRequest.php',
        'HotelCodesResponse' => __DIR__ .'/HotelCodesResponse.php',
        'ArrayOfHotels' => __DIR__ .'/ArrayOfHotels.php',
        'Hotels' => __DIR__ .'/Hotels.php',
        'HotelSearchWithRoomsRequest' => __DIR__ .'/HotelSearchWithRoomsRequest.php',
        'HotelSearchWithRoomsResponse' => __DIR__ .'/HotelSearchWithRoomsResponse.php',
        'ArrayOfHotel_ResultWithRooms' => __DIR__ .'/ArrayOfHotel_ResultWithRooms.php',
        'Hotel_ResultWithRooms' => __DIR__ .'/Hotel_ResultWithRooms.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_aefdbdded44c7c4ce86e33e56c69d662');

// Do nothing. The rest is just leftovers from the code generation.
{
}
